- alias: Outside Lights (AWAY)
  trigger:
    platform: state
    entity_id: device_tracker.alexs_phone_owntracks
    from: home
    to: not_home
  condition:
    condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
    entity_id: group.outside_lights
    service: switch.turn_on
- alias: Outside Lights (HOME)
  trigger:
    platform: state
    entity_id: device_tracker.alexs_phone_owntracks
    from: not_home
    to: home
  condition:
    condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - service: switch.turn_off
    data:
      entity_id: group.outside_lights
  - service: light.turn_on
    data:
      entity_id: group.kitchen_lights
  - service: light.turn_on
    data:
      entity_id: group.living_room_lights
- alias: Outside Lights (SUNSET)
  trigger:
    platform: sun
    event: sunset
  condition:
    condition: state
    entity_id: device_tracker.alexs_phone_owntracks
    state: not_home
  action:
    entity_id: group.outside_lights
    service: switch.turn_on
- alias: All Lights (SUNRISE)
  trigger:
  - event: sunrise
    platform: sun
  action:
  - service: switch.turn_off
    entity_id: all
  - service: light.turn_off
    entity_id: all
  mode: single
- alias: Inside Lights (SUNSET)
  trigger:
    platform: sun
    event: sunset
  condition:
    condition: state
    entity_id: device_tracker.alexs_phone_owntracks
    state: home
  action:
  - service: light.turn_on
    data:
      entity_id: group.kitchen_lights
  - service: light.turn_on
    data:
      entity_id: group.living_room_lights
