- id: '1553912216011'
  alias: Outside Lights (AWAY)
  trigger:
  - entity_id: device_tracker.alexs_iphone
    from: home
    platform: state
    to: not_home
  - entity_id: device_tracker.alexs_iphone_ios
    from: home
    platform: state
    to: not_home
  - entity_id: device_tracker.alexs_phone_owntracks
    from: home
    platform: state
    to: not_home
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - alias: ''
    data:
      entity_id: group.outside_lights
    service: switch.turn_on
- id: '1553924030288'
  alias: Outside Lights (HOME)
  trigger:
  - entity_id: device_tracker.alexs_iphone
    from: not_home
    platform: state
    to: home
  - entity_id: device_tracker.alexs_iphone_ios
    from: not_home
    platform: state
    to: home
  - entity_id: device_tracker.alexs_phone_owntracks
    from: not_home
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data:
      entity_id: group.outside_lights
    service: switch.turn_off
  - data:
      entity_id: group.kitchen_lights
    service: light.turn_on
  - data:
      entity_id: group.living_room_lights
    service: light.turn_on
- id: '1553926941290'
  alias: Outside Lights (SUNSET)
  trigger:
  - event: sunset
    platform: sun
  condition:
  - condition: state
    entity_id: device_tracker.alexs_phone
    state: not_home
  - condition: state
    entity_id: device_tracker.alexs_iphone_ios
    state: not_home
  - condition: state
    entity_id: device_tracker.alexs_phone_owntracks
    state: not_home
  action:
  - data:
      entity_id: group.outside_lights
    service: switch.turn_on
- id: '1553927002363'
  alias: All Lights (SUNRISE)
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - data: {}
    service: switch.turn_off
  - data: {}
    service: light.turn_off
- id: '1555984346145'
  alias: Inside Lights (SUNSET)
  trigger:
  - event: sunset
    platform: sun
  condition:
  - condition: state
    entity_id: device_tracker.alexs_phone
    state: home
  - condition: state
    entity_id: device_tracker.alexs_iphone_ios
    state: home
  - condition: state
    entity_id: device_tracker.alexs_phone_owntracks
    state: home
  action:
  - data:
      entity_id: group.kitchen_lights
    service: light.turn_on
  - data:
      entity_id: group.living_room_lights
    service: light.turn_on
